// Copyright 2020 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_database_hash                    6
#define gattdb_client_support_features          8
#define gattdb_device_name                     11
#define gattdb_xgatt_gpio_pb0                  23
#define gattdb_xgatt_gpio_pb1                  26
#define gattdb_xgatt_gpio_led0                 29
#define gattdb_xgatt_gpio_led1                 32
#define gattdb_xgatt_gpio_PWM1                 35
#define gattdb_xgatt_gpio_ADC0                 38
#define gattdb_ota_control                     42

#endif
